services:
  kamailio:
    image: ghcr.io/kamailio/kamailio:6.0.3-focal
    container_name: kamailio
    networks:
      sipnet:
        aliases:        
          - sipnet.kamailio  # DNS name and a server for both:
          - acme.operator    #  acme.operator, and 
    environment:
      - SIP_DOMAIN=acme.operator
      - WITH_DB=no
    volumes:
      - ./scripts_aux/app.cfg:/etc/kamailio/kamailio.cfg:ro
      - ./scripts/registrar-b2bua.py:/etc/kamailio/app.py:ro
      # Add volume for persistent htable data
      - kamailio_data:/var/kamailio/db
    restart: unless-stopped

  terminal_alice:
    image: twinkle:igrs_01
    container_name: twinkle_alice
    networks:
      - sipnet
    hostname: sipnet.alice
    environment:
      - DISPLAY=${DISPLAY}
    entrypoint: ["sh", "/root/start.sh"]
    volumes:
      - ./scripts/Alice.cfg:/tmp/twinkle/Alice.cfg:ro
      - ./scripts/twinkle_alice.sys:/tmp/twinkle/twinkle.sys:ro
      - ./scripts_aux/.asoundrc:/root/.asoundrc:ro
      - ./scripts_aux/start.sh:/root/start.sh:ro
      - twinkle-alice:/root/.twinkle
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:rw
    restart: unless-stopped

  terminal_bob:
    image: twinkle:igrs_01
    container_name: twinkle_bob
    networks:
      - sipnet
    hostname: sipnet.bob
    environment:
      - DISPLAY=${DISPLAY}
    entrypoint: ["sh", "/root/start.sh"]
    volumes:
      - ./scripts/Bob.cfg:/tmp/twinkle/Bob.cfg:ro
      - ./scripts/twinkle_bob.sys:/tmp/twinkle/twinkle.sys:ro
      - ./scripts_aux/.asoundrc:/root/.asoundrc:ro
      - ./scripts_aux/start.sh:/root/start.sh:ro
      - twinkle-bob:/root/.twinkle
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:rw
    restart: unless-stopped

  terminal_john:
    image: twinkle:igrs_01
    container_name: twinkle_john
    networks:
      - sipnet
    hostname: sipnet.john
    environment:
      - DISPLAY=${DISPLAY}
    entrypoint: ["sh", "/root/start.sh"]
    volumes:
      - ./scripts/John.cfg:/tmp/twinkle/John.cfg:ro
      - ./scripts/twinkle_john.sys:/tmp/twinkle/twinkle.sys:ro
      - ./scripts_aux/.asoundrc:/root/.asoundrc:ro
      - ./scripts_aux/start.sh:/root/start.sh:ro
      - twinkle-john:/root/.twinkle
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:rw
    restart: unless-stopped

networks:
  sipnet:
    driver: bridge

volumes:
  twinkle-alice:
  twinkle-bob:
  twinkle-john:
  kamailio_data:  # Add volume for persistent data